// 78 Tarot Cards Data - Rider-Waite Deck
// Major Arcana (22 cards) + Minor Arcana (56 cards: 14 of each suit)

// Helper function to generate card image URL
// Using placeholder images for demo purposes
// In production, replace with actual Rider-Waite card images
const getCardImageUrl = (filename) => {
  // Using placeholder service that shows card identifier
  // Replace this with your own hosted images or reliable CDN
  return `https://placehold.co/300x500/1a1a2e/9d4edd?text=${encodeURIComponent(filename.toUpperCase())}`;
};

const tarotCards = [
  // ========== MAJOR ARCANA (22 cards) ==========
  {
    id: 0,
    name: "The Fool",
    nameUk: "Дурень",
    suit: "Major Arcana",
    number: 0,
    meaningUpright: "New beginnings, innocence, spontaneity, free spirit, adventure",
    meaningUprightUk: "Нові початки, невинність, спонтанність, вільний дух, пригоди",
    meaningReversed: "Naivety, foolishness, recklessness, risk-taking, lack of direction",
    meaningReversedUk: "Наївність, безрозсудність, ризикованість, відсутність напрямку",
    keywords: ["beginnings", "freedom", "innocence", "adventure"],
    keywordsUk: ["початок", "свобода", "невинність", "пригода"],
    image: getCardImageUrl("ar00")
  },
  {
    id: 1,
    name: "The Magician",
    nameUk: "Маг",
    suit: "Major Arcana",
    number: 1,
    meaningUpright: "Manifestation, resourcefulness, power, inspired action, skill",
    meaningUprightUk: "Втілення, винахідливість, сила, натхненні дії, майстерність",
    meaningReversed: "Manipulation, poor planning, untapped talents, trickery",
    meaningReversedUk: "Маніпуляція, погане планування, нереалізований талант, хитрість",
    keywords: ["manifestation", "power", "action", "creativity"],
    keywordsUk: ["втілення", "сила", "дія", "творчість"],
    image: getCardImageUrl("ar01")
  },
  {
    id: 2,
    name: "The High Priestess",
    nameUk: "Верховна Жриця",
    suit: "Major Arcana",
    number: 2,
    meaningUpright: "Intuition, sacred knowledge, divine feminine, subconscious mind",
    meaningUprightUk: "Інтуїція, священне знання, божественна жіночність, підсвідомість",
    meaningReversed: "Secrets, disconnected from intuition, withdrawal, silence",
    meaningReversedUk: "Секрети, відключення від інтуїції, відчуження, мовчання",
    keywords: ["intuition", "mystery", "wisdom", "subconscious"],
    keywordsUk: ["інтуїція", "таємниця", "мудрість", "підсвідомість"],
    image: getCardImageUrl("ar02")
  },
  {
    id: 3,
    name: "The Empress",
    nameUk: "Імператриця",
    suit: "Major Arcana",
    number: 3,
    meaningUpright: "Femininity, beauty, nature, nurturing, abundance, creativity",
    meaningUprightUk: "Жіночність, краса, природа, турбота, достаток, творчість",
    meaningReversed: "Creative block, dependence on others, smothering, lack of growth",
    meaningReversedUk: "Творчий блок, залежність, надмірна опіка, відсутність росту",
    keywords: ["abundance", "nurturing", "fertility", "nature"],
    keywordsUk: ["достаток", "турбота", "плодючість", "природа"],
    image: getCardImageUrl("ar03")
  },
  {
    id: 4,
    name: "The Emperor",
    nameUk: "Імператор",
    suit: "Major Arcana",
    number: 4,
    meaningUpright: "Authority, establishment, structure, father figure, leadership",
    meaningUprightUk: "Авторитет, встановлення, структура, батьківська фігура, лідерство",
    meaningReversed: "Domination, excessive control, rigidity, inflexibility, tyranny",
    meaningReversedUk: "Домінування, надмірний контроль, жорсткість, негнучкість, тиранія",
    keywords: ["authority", "structure", "control", "leadership"],
    keywordsUk: ["авторитет", "структура", "контроль", "лідерство"],
    image: getCardImageUrl("ar04")
  },
  {
    id: 5,
    name: "The Hierophant",
    nameUk: "Верховний Жрець",
    suit: "Major Arcana",
    number: 5,
    meaningUpright: "Spiritual wisdom, tradition, institutions, conformity, religious beliefs",
    meaningUprightUk: "Духовна мудрість, традиції, інституції, конформізм, релігійні вірування",
    meaningReversed: "Personal beliefs, freedom, challenging status quo, unconventional",
    meaningReversedUk: "Особисті переконання, свобода, виклик статус-кво, нетрадиційність",
    keywords: ["tradition", "conformity", "spirituality", "institutions"],
    keywordsUk: ["традиція", "конформізм", "духовність", "інституції"],
    image: getCardImageUrl("ar05")
  },
  {
    id: 6,
    name: "The Lovers",
    nameUk: "Закохані",
    suit: "Major Arcana",
    number: 6,
    meaningUpright: "Love, harmony, relationships, values alignment, choices, union",
    meaningUprightUk: "Кохання, гармонія, стосунки, узгодження цінностей, вибір, союз",
    meaningReversed: "Self-love, disharmony, imbalance, misalignment of values, broken relationship",
    meaningReversedUk: "Самолюбство, дисгармонія, дисбаланс, невідповідність цінностей, розрив",
    keywords: ["love", "harmony", "union", "choices"],
    keywordsUk: ["кохання", "гармонія", "союз", "вибір"],
    image: getCardImageUrl("ar06")
  },
  {
    id: 7,
    name: "The Chariot",
    nameUk: "Колісниця",
    suit: "Major Arcana",
    number: 7,
    meaningUpright: "Control, willpower, success, action, determination, victory",
    meaningUprightUk: "Контроль, сила волі, успіх, дія, рішучість, перемога",
    meaningReversed: "Lack of control, lack of direction, aggression, opposition",
    meaningReversedUk: "Відсутність контролю, відсутність напрямку, агресія, опозиція",
    keywords: ["victory", "determination", "control", "success"],
    keywordsUk: ["перемога", "рішучість", "контроль", "успіх"],
    image: getCardImageUrl("ar07")
  },
  {
    id: 8,
    name: "Strength",
    nameUk: "Сила",
    suit: "Major Arcana",
    number: 8,
    meaningUpright: "Courage, bravery, confidence, inner strength, compassion, influence",
    meaningUprightUk: "Мужність, хоробрість, впевненість, внутрішня сила, співчуття, вплив",
    meaningReversed: "Self-doubt, weakness, insecurity, low confidence, lack of courage",
    meaningReversedUk: "Сумніви, слабкість, невпевненість, низька самооцінка, відсутність мужності",
    keywords: ["courage", "confidence", "inner-strength", "compassion"],
    keywordsUk: ["мужність", "впевненість", "внутрішня-сила", "співчуття"],
    image: getCardImageUrl("ar08")
  },
  {
    id: 9,
    name: "The Hermit",
    nameUk: "Відлюдник",
    suit: "Major Arcana",
    number: 9,
    meaningUpright: "Soul-searching, introspection, inner guidance, solitude, spiritual enlightenment",
    meaningUprightUk: "Пошук себе, самоаналіз, внутрішнє керівництво, самотність, духовне просвітлення",
    meaningReversed: "Isolation, loneliness, withdrawal, lost your way, paranoia",
    meaningReversedUk: "Ізоляція, самотність, відчуження, втрата шляху, паранойя",
    keywords: ["introspection", "solitude", "wisdom", "guidance"],
    keywordsUk: ["самоаналіз", "самотність", "мудрість", "керівництво"],
    image: getCardImageUrl("ar09")
  },
  {
    id: 10,
    name: "Wheel of Fortune",
    nameUk: "Колесо Фортуни",
    suit: "Major Arcana",
    number: 10,
    meaningUpright: "Good luck, karma, life cycles, destiny, turning point, change",
    meaningUprightUk: "Удача, карма, життєві цикли, доля, поворотний момент, зміни",
    meaningReversed: "Bad luck, resistance to change, breaking cycles, lack of control",
    meaningReversedUk: "Невдача, опір змінам, розрив циклів, відсутність контролю",
    keywords: ["luck", "destiny", "change", "cycles"],
    keywordsUk: ["удача", "доля", "зміни", "цикли"],
    image: getCardImageUrl("ar10")
  },
  {
    id: 11,
    name: "Justice",
    nameUk: "Справедливість",
    suit: "Major Arcana",
    number: 11,
    meaningUpright: "Justice, fairness, truth, cause and effect, law, accountability",
    meaningUprightUk: "Справедливість, чесність, правда, причина і наслідок, закон, відповідальність",
    meaningReversed: "Unfairness, lack of accountability, dishonesty, legal complications",
    meaningReversedUk: "Несправедливість, відсутність відповідальності, нечесність, юридичні ускладнення",
    keywords: ["justice", "fairness", "truth", "law"],
    keywordsUk: ["справедливість", "чесність", "правда", "закон"],
    image: getCardImageUrl("ar11")
  },
  {
    id: 12,
    name: "The Hanged Man",
    nameUk: "Повішений",
    suit: "Major Arcana",
    number: 12,
    meaningUpright: "Pause, surrender, letting go, new perspectives, waiting, sacrifice",
    meaningUprightUk: "Пауза, капітуляція, відпускання, нові перспективи, очікування, жертва",
    meaningReversed: "Delays, resistance, stalling, indecision, stagnation, wasted effort",
    meaningReversedUk: "Затримки, опір, застій, нерішучість, стагнація, марні зусилля",
    keywords: ["pause", "surrender", "perspective", "sacrifice"],
    keywordsUk: ["пауза", "капітуляція", "перспектива", "жертва"],
    image: getCardImageUrl("ar12")
  },
  {
    id: 13,
    name: "Death",
    nameUk: "Смерть",
    suit: "Major Arcana",
    number: 13,
    meaningUpright: "Endings, change, transformation, transition, letting go, rebirth",
    meaningUprightUk: "Завершення, зміни, трансформація, перехід, відпускання, відродження",
    meaningReversed: "Resistance to change, inability to move on, holding on, stagnation",
    meaningReversedUk: "Опір змінам, нездатність рухатися далі, утримування, застій",
    keywords: ["transformation", "endings", "change", "rebirth"],
    keywordsUk: ["трансформація", "завершення", "зміни", "відродження"],
    image: getCardImageUrl("ar13")
  },
  {
    id: 14,
    name: "Temperance",
    nameUk: "Поміркованість",
    suit: "Major Arcana",
    number: 14,
    meaningUpright: "Balance, moderation, patience, purpose, meaning, harmony",
    meaningUprightUk: "Баланс, поміркованість, терпіння, мета, значення, гармонія",
    meaningReversed: "Imbalance, excess, lack of long-term vision, self-indulgence",
    meaningReversedUk: "Дисбаланс, надмірність, відсутність довгострокового бачення, самовдоволення",
    keywords: ["balance", "moderation", "patience", "harmony"],
    keywordsUk: ["баланс", "поміркованість", "терпіння", "гармонія"],
    image: getCardImageUrl("ar14")
  },
  {
    id: 15,
    name: "The Devil",
    nameUk: "Диявол",
    suit: "Major Arcana",
    number: 15,
    meaningUpright: "Shadow self, attachment, addiction, restriction, sexuality, materialism",
    meaningUprightUk: "Тіньове я, прив'язаність, залежність, обмеження, сексуальність, матеріалізм",
    meaningReversed: "Releasing limiting beliefs, exploring dark thoughts, detachment, freedom",
    meaningReversedUk: "Звільнення від обмежувальних переконань, дослідження темних думок, відчуження, свобода",
    keywords: ["bondage", "addiction", "materialism", "shadow"],
    keywordsUk: ["залежність", "наркоманія", "матеріалізм", "тінь"],
    image: getCardImageUrl("ar15")
  },
  {
    id: 16,
    name: "The Tower",
    nameUk: "Вежа",
    suit: "Major Arcana",
    number: 16,
    meaningUpright: "Sudden change, upheaval, chaos, revelation, awakening, destruction",
    meaningUprightUk: "Раптові зміни, потрясіння, хаос, одкровення, пробудження, руйнування",
    meaningReversed: "Personal transformation, fear of change, averting disaster, delayed disaster",
    meaningReversedUk: "Особиста трансформація, страх змін, запобігання катастрофі, відкладена катастрофа",
    keywords: ["upheaval", "chaos", "revelation", "awakening"],
    keywordsUk: ["потрясіння", "хаос", "одкровення", "пробудження"],
    image: getCardImageUrl("ar16")
  },
  {
    id: 17,
    name: "The Star",
    nameUk: "Зірка",
    suit: "Major Arcana",
    number: 17,
    meaningUpright: "Hope, faith, purpose, renewal, spirituality, inspiration, serenity",
    meaningUprightUk: "Надія, віра, мета, оновлення, духовність, натхнення, спокій",
    meaningReversed: "Lack of faith, despair, self-trust, disconnection, hopelessness",
    meaningReversedUk: "Відсутність віри, відчай, довіра до себе, роз'єднання, безнадія",
    keywords: ["hope", "inspiration", "spirituality", "renewal"],
    keywordsUk: ["надія", "натхнення", "духовність", "оновлення"],
    image: getCardImageUrl("ar17")
  },
  {
    id: 18,
    name: "The Moon",
    nameUk: "Місяць",
    suit: "Major Arcana",
    number: 18,
    meaningUpright: "Illusion, fear, anxiety, subconscious, intuition, dreams, confusion",
    meaningUprightUk: "Ілюзія, страх, тривога, підсвідомість, інтуїція, сни, плутанина",
    meaningReversed: "Release of fear, repressed emotion, inner confusion, clarity",
    meaningReversedUk: "Звільнення від страху, придушені емоції, внутрішня плутанина, ясність",
    keywords: ["illusion", "intuition", "fear", "dreams"],
    keywordsUk: ["ілюзія", "інтуїція", "страх", "сни"],
    image: getCardImageUrl("ar18")
  },
  {
    id: 19,
    name: "The Sun",
    nameUk: "Сонце",
    suit: "Major Arcana",
    number: 19,
    meaningUpright: "Positivity, fun, warmth, success, vitality, joy, abundance",
    meaningUprightUk: "Позитив, веселощі, тепло, успіх, життєва сила, радість, достаток",
    meaningReversed: "Inner child, feeling down, overly optimistic, temporary depression",
    meaningReversedUk: "Внутрішня дитина, пригнічення, надмірний оптимізм, тимчасова депресія",
    keywords: ["joy", "success", "vitality", "positivity"],
    keywordsUk: ["радість", "успіх", "життєва-сила", "позитив"],
    image: getCardImageUrl("ar19")
  },
  {
    id: 20,
    name: "Judgement",
    nameUk: "Суд",
    suit: "Major Arcana",
    number: 20,
    meaningUpright: "Judgement, rebirth, inner calling, absolution, awakening, reflection",
    meaningUprightUk: "Судження, відродження, внутрішній заклик, відпущення, пробудження, роздуми",
    meaningReversed: "Self-doubt, inner critic, ignoring the call, lack of self-awareness",
    meaningReversedUk: "Сумніви у собі, внутрішній критик, ігнорування заклику, відсутність самосвідомості",
    keywords: ["judgement", "rebirth", "awakening", "reflection"],
    keywordsUk: ["судження", "відродження", "пробудження", "роздуми"],
    image: getCardImageUrl("ar20")
  },
  {
    id: 21,
    name: "The World",
    nameUk: "Світ",
    suit: "Major Arcana",
    number: 21,
    meaningUpright: "Completion, integration, accomplishment, travel, fulfillment, wholeness",
    meaningUprightUk: "Завершення, інтеграція, досягнення, подорож, виконання, цілісність",
    meaningReversed: "Seeking closure, incompletion, delays, short-cuts, lack of achievement",
    meaningReversedUk: "Пошук завершення, незавершеність, затримки, обхідні шляхи, відсутність досягнень",
    keywords: ["completion", "achievement", "travel", "fulfillment"],
    keywordsUk: ["завершення", "досягнення", "подорож", "виконання"],
    image: getCardImageUrl("ar21")
  },

  // ========== CUPS (14 cards) ==========
  {
    id: 22,
    name: "Ace of Cups",
    nameUk: "Туз Кубків",
    suit: "Cups",
    number: 1,
    meaningUpright: "Love, new relationships, compassion, creativity, emotional abundance",
    meaningUprightUk: "Кохання, нові стосунки, співчуття, творчість, емоційний достаток",
    meaningReversed: "Self-love, intuition, repressed emotions, blocked creativity",
    meaningReversedUk: "Самолюбство, інтуїція, придушені емоції, блокована творчість",
    keywords: ["love", "emotions", "new-feelings", "compassion"],
    keywordsUk: ["кохання", "емоції", "нові-почуття", "співчуття"],
    image: getCardImageUrl("cu01")
  },
  {
    id: 23,
    name: "Two of Cups",
    nameUk: "Двійка Кубків",
    suit: "Cups",
    number: 2,
    meaningUpright: "Unified love, partnership, mutual attraction, relationships, connection",
    meaningUprightUk: "Єдине кохання, партнерство, взаємне притягнення, стосунки, зв'язок",
    meaningReversed: "Self-love, break-ups, disharmony, distrust, imbalance",
    meaningReversedUk: "Самолюбство, розриви, дисгармонія, недовіра, дисбаланс",
    keywords: ["partnership", "unity", "love", "connection"],
    keywordsUk: ["партнерство", "єдність", "кохання", "зв'язок"],
    image: getCardImageUrl("cu02")
  },
  {
    id: 24,
    name: "Three of Cups",
    nameUk: "Трійка Кубків",
    suit: "Cups",
    number: 3,
    meaningUpright: "Celebration, friendship, creativity, collaborations, community, gatherings",
    meaningUprightUk: "Святкування, дружба, творчість, співпраця, спільнота, збори",
    meaningReversed: "Independence, alone time, hardcore partying, three's a crowd",
    meaningReversedUk: "Незалежність, час наодинці, важкі вечірки, третій зайвий",
    keywords: ["celebration", "friendship", "community", "joy"],
    keywordsUk: ["святкування", "дружба", "спільнота", "радість"],
    image: getCardImageUrl("cu03")
  },
  {
    id: 25,
    name: "Four of Cups",
    nameUk: "Четвірка Кубків",
    suit: "Cups",
    number: 4,
    meaningUpright: "Meditation, contemplation, apathy, reevaluation, boredom, discontent",
    meaningUprightUk: "Медитація, споглядання, апатія, переоцінка, нудьга, незадоволення",
    meaningReversed: "Retreat, withdrawal, checking in for alignment, new opportunities",
    meaningReversedUk: "Відступ, відчуження, перевірка узгодження, нові можливості",
    keywords: ["apathy", "contemplation", "reevaluation", "discontent"],
    keywordsUk: ["апатія", "споглядання", "переоцінка", "незадоволення"],
    image: getCardImageUrl("cu04")
  },
  {
    id: 26,
    name: "Five of Cups",
    nameUk: "П'ятірка Кубків",
    suit: "Cups",
    number: 5,
    meaningUpright: "Regret, failure, disappointment, pessimism, loss, grief",
    meaningUprightUk: "Жаль, невдача, розчарування, песимізм, втрата, горе",
    meaningReversed: "Personal setbacks, self-forgiveness, moving on, acceptance",
    meaningReversedUk: "Особисті невдачі, самопрощення, рухатися далі, прийняття",
    keywords: ["loss", "regret", "disappointment", "grief"],
    keywordsUk: ["втрата", "жаль", "розчарування", "горе"],
    image: getCardImageUrl("cu05")
  },
  {
    id: 27,
    name: "Six of Cups",
    nameUk: "Шістка Кубків",
    suit: "Cups",
    number: 6,
    meaningUpright: "Revisiting the past, childhood memories, innocence, nostalgia, reunion",
    meaningUprightUk: "Перегляд минулого, дитячі спогади, невинність, ностальгія, возз'єднання",
    meaningReversed: "Living in past, forgiveness, lacking playfulness, being stuck",
    meaningReversedUk: "Життя в минулому, прощення, відсутність грайливості, застрягання",
    keywords: ["nostalgia", "memories", "innocence", "reunion"],
    keywordsUk: ["ностальгія", "спогади", "невинність", "возз'єднання"],
    image: getCardImageUrl("cu06")
  },
  {
    id: 28,
    name: "Seven of Cups",
    nameUk: "Сімка Кубків",
    suit: "Cups",
    number: 7,
    meaningUpright: "Opportunities, choices, wishful thinking, illusion, fantasy, daydreaming",
    meaningUprightUk: "Можливості, вибір, думки-побажання, ілюзія, фантазія, мрійництво",
    meaningReversed: "Alignment, personal values, overwhelmed by choices, clarity",
    meaningReversedUk: "Узгодження, особисті цінності, перевантаженість виборами, ясність",
    keywords: ["choices", "illusion", "fantasy", "opportunities"],
    keywordsUk: ["вибір", "ілюзія", "фантазія", "можливості"],
    image: getCardImageUrl("cu07")
  },
  {
    id: 29,
    name: "Eight of Cups",
    nameUk: "Вісімка Кубків",
    suit: "Cups",
    number: 8,
    meaningUpright: "Disappointment, abandonment, withdrawal, escapism, searching for truth",
    meaningUprightUk: "Розчарування, покинутість, відчуження, втеча від реальності, пошук правди",
    meaningReversed: "Trying one more time, indecision, aimless drifting, walking away",
    meaningReversedUk: "Спроба ще раз, нерішучість, безцільне дрейфування, відходження",
    keywords: ["disappointment", "withdrawal", "seeking-truth", "abandonment"],
    keywordsUk: ["розчарування", "відчуження", "пошук-правди", "покинутість"],
    image: getCardImageUrl("cu08")
  },
  {
    id: 30,
    name: "Nine of Cups",
    nameUk: "Дев'ятка Кубків",
    suit: "Cups",
    number: 9,
    meaningUpright: "Contentment, satisfaction, gratitude, wish come true, luxury, self-satisfaction",
    meaningUprightUk: "Задоволення, вдоволення, вдячність, виконання бажань, розкіш, самовдоволення",
    meaningReversed: "Inner happiness, materialism, dissatisfaction, greed, superficiality",
    meaningReversedUk: "Внутрішнє щастя, матеріалізм, незадоволення, жадібність, поверхневість",
    keywords: ["satisfaction", "wishes", "contentment", "gratitude"],
    keywordsUk: ["задоволення", "бажання", "вдоволення", "вдячність"],
    image: getCardImageUrl("cu09")
  },
  {
    id: 31,
    name: "Ten of Cups",
    nameUk: "Десятка Кубків",
    suit: "Cups",
    number: 10,
    meaningUpright: "Divine love, bliss, harmony, alignment, family, happy relationships",
    meaningUprightUk: "Божественне кохання, блаженство, гармонія, узгодження, сім'я, щасливі стосунки",
    meaningReversed: "Disconnection, misaligned values, struggling relationships, disharmony",
    meaningReversedUk: "Роз'єднання, неузгоджені цінності, важкі стосунки, дисгармонія",
    keywords: ["happiness", "harmony", "family", "fulfillment"],
    keywordsUk: ["щастя", "гармонія", "сім'я", "виконання"],
    image: getCardImageUrl("cu10")
  },
  {
    id: 32,
    name: "Page of Cups",
    nameUk: "Паж Кубків",
    suit: "Cups",
    number: 11,
    meaningUpright: "Creative opportunities, intuitive messages, curiosity, possibility, new ideas",
    meaningUprightUk: "Творчі можливості, інтуїтивні повідомлення, цікавість, можливість, нові ідеї",
    meaningReversed: "New ideas, doubting intuition, creative blocks, emotional immaturity",
    meaningReversedUk: "Нові ідеї, сумніви в інтуїції, творчі блоки, емоційна незрілість",
    keywords: ["creativity", "intuition", "curiosity", "new-ideas"],
    keywordsUk: ["творчість", "інтуїція", "цікавість", "нові-ідеї"],
    image: getCardImageUrl("cu11")
  },
  {
    id: 33,
    name: "Knight of Cups",
    nameUk: "Лицар Кубків",
    suit: "Cups",
    number: 12,
    meaningUpright: "Romance, charm, imagination, beauty, following the heart, idealism",
    meaningUprightUk: "Романтика, чарівність, уява, краса, слідування за серцем, ідеалізм",
    meaningReversed: "Overactive imagination, unrealistic, jealous, moody, disappointment",
    meaningReversedUk: "Надмірна уява, нереалістичність, ревнощі, настрої, розчарування",
    keywords: ["romance", "charm", "idealism", "beauty"],
    keywordsUk: ["романтика", "чарівність", "ідеалізм", "краса"],
    image: getCardImageUrl("cu12")
  },
  {
    id: 34,
    name: "Queen of Cups",
    nameUk: "Королева Кубків",
    suit: "Cups",
    number: 13,
    meaningUpright: "Compassion, warmth, kindness, intuition, healer, counselor, support",
    meaningUprightUk: "Співчуття, тепло, доброта, інтуїція, цілитель, порадник, підтримка",
    meaningReversed: "Inner feelings, self-care, self-love, codependency, giving too much",
    meaningReversedUk: "Внутрішні почуття, самодопомога, самолюбство, співзалежність, надмірна віддача",
    keywords: ["compassion", "intuition", "nurturing", "healing"],
    keywordsUk: ["співчуття", "інтуїція", "турбота", "зцілення"],
    image: getCardImageUrl("cu13")
  },
  {
    id: 35,
    name: "King of Cups",
    nameUk: "Король Кубків",
    suit: "Cups",
    number: 14,
    meaningUpright: "Emotional balance, control, compassion, diplomacy, wise, calm, tolerant",
    meaningUprightUk: "Емоційний баланс, контроль, співчуття, дипломатія, мудрість, спокій, толерантність",
    meaningReversed: "Self-compassion, inner feelings, moodiness, emotional manipulation",
    meaningReversedUk: "Співчуття до себе, внутрішні почуття, настрійність, емоційна маніпуляція",
    keywords: ["emotional-balance", "compassion", "diplomacy", "wisdom"],
    keywordsUk: ["емоційний-баланс", "співчуття", "дипломатія", "мудрість"],
    image: getCardImageUrl("cu14")
  },

  // ========== SWORDS (14 cards) ==========
  {
    id: 36,
    name: "Ace of Swords",
    nameUk: "Туз Мечів",
    suit: "Swords",
    number: 1,
    meaningUpright: "Breakthroughs, new ideas, mental clarity, success, raw intelligence",
    meaningUprightUk: "Прориви, нові ідеї, ментальна ясність, успіх, чистий інтелект",
    meaningReversed: "Inner clarity, re-thinking ideas, clouded judgement, confusion",
    meaningReversedUk: "Внутрішня ясність, переосмислення ідей, затьмарене судження, плутанина",
    keywords: ["clarity", "breakthrough", "ideas", "success"],
    keywordsUk: ["ясність", "прорив", "ідеї", "успіх"],
    image: getCardImageUrl("sw01")
  },
  {
    id: 37,
    name: "Two of Swords",
    nameUk: "Двійка Мечів",
    suit: "Swords",
    number: 2,
    meaningUpright: "Difficult decisions, weighing options, stalemate, avoidance, denial",
    meaningUprightUk: "Важкі рішення, зважування варіантів, глухий кут, уникнення, заперечення",
    meaningReversed: "Indecision, confusion, information overload, stalemate, difficult choices",
    meaningReversedUk: "Нерішучість, плутанина, інформаційне перевантаження, глухий кут, важкі вибори",
    keywords: ["decisions", "stalemate", "avoidance", "choices"],
    keywordsUk: ["рішення", "глухий-кут", "уникнення", "вибори"],
    image: getCardImageUrl("sw02")
  },
  {
    id: 38,
    name: "Three of Swords",
    nameUk: "Трійка Мечів",
    suit: "Swords",
    number: 3,
    meaningUpright: "Heartbreak, emotional pain, sorrow, grief, hurt, betrayal, suffering",
    meaningUprightUk: "Розбите серце, емоційний біль, смуток, горе, страждання, зрада, біль",
    meaningReversed: "Negative self-talk, releasing pain, optimism, forgiveness, healing",
    meaningReversedUk: "Негативний внутрішній діалог, звільнення від болю, оптимізм, прощення, зцілення",
    keywords: ["heartbreak", "pain", "sorrow", "betrayal"],
    keywordsUk: ["розбите-серце", "біль", "смуток", "зрада"],
    image: getCardImageUrl("sw03")
  },
  {
    id: 39,
    name: "Four of Swords",
    nameUk: "Четвірка Мечів",
    suit: "Swords",
    number: 4,
    meaningUpright: "Rest, relaxation, meditation, contemplation, recuperation, recovery",
    meaningUprightUk: "Відпочинок, релаксація, медитація, споглядання, відновлення, одужання",
    meaningReversed: "Exhaustion, burn-out, deep contemplation, stagnation, restlessness",
    meaningReversedUk: "Виснаження, вигорання, глибоке споглядання, застій, неспокій",
    keywords: ["rest", "recovery", "meditation", "contemplation"],
    keywordsUk: ["відпочинок", "одужання", "медитація", "споглядання"],
    image: getCardImageUrl("sw04")
  },
  {
    id: 40,
    name: "Five of Swords",
    nameUk: "П'ятірка Мечів",
    suit: "Swords",
    number: 5,
    meaningUpright: "Conflict, disagreements, competition, defeat, win at all costs, betrayal",
    meaningUprightUk: "Конфлікт, розбіжності, конкуренція, поразка, перемога за будь-яку ціну, зрада",
    meaningReversed: "Reconciliation, making amends, past resentment, open communication",
    meaningReversedUk: "Примирення, виправлення помилок, минула образа, відкрите спілкування",
    keywords: ["conflict", "defeat", "competition", "betrayal"],
    keywordsUk: ["конфлікт", "поразка", "конкуренція", "зрада"],
    image: getCardImageUrl("sw05")
  },
  {
    id: 41,
    name: "Six of Swords",
    nameUk: "Шістка Мечів",
    suit: "Swords",
    number: 6,
    meaningUpright: "Transition, change, rite of passage, releasing baggage, moving forward",
    meaningUprightUk: "Перехід, зміни, ритуал переходу, звільнення від тягаря, рух вперед",
    meaningReversed: "Personal transition, resistance to change, unfinished business",
    meaningReversedUk: "Особистий перехід, опір змінам, незавершені справи",
    keywords: ["transition", "change", "moving-on", "release"],
    keywordsUk: ["перехід", "зміни", "рух-вперед", "звільнення"],
    image: getCardImageUrl("sw06")
  },
  {
    id: 42,
    name: "Seven of Swords",
    nameUk: "Сімка Мечів",
    suit: "Swords",
    number: 7,
    meaningUpright: "Betrayal, deception, getting away with something, stealth, cunning",
    meaningUprightUk: "Зрада, обман, уникнення відповідальності, скритність, хитрість",
    meaningReversed: "Imposter syndrome, self-deceit, keeping secrets, coming clean",
    meaningReversedUk: "Синдром самозванця, самообман, зберігання секретів, чесність",
    keywords: ["betrayal", "deception", "stealth", "cunning"],
    keywordsUk: ["зрада", "обман", "скритність", "хитрість"],
    image: getCardImageUrl("sw07")
  },
  {
    id: 43,
    name: "Eight of Swords",
    nameUk: "Вісімка Мечів",
    suit: "Swords",
    number: 8,
    meaningUpright: "Negative thoughts, self-imposed restriction, imprisonment, victim mentality",
    meaningUprightUk: "Негативні думки, самообмеження, ув'язнення, менталітет жертви",
    meaningReversed: "Self-limiting beliefs, inner critic, releasing negative thoughts, open to options",
    meaningReversedUk: "Самообмежувальні переконання, внутрішній критик, звільнення від негативних думок, відкритість до варіантів",
    keywords: ["restriction", "imprisonment", "victim", "negativity"],
    keywordsUk: ["обмеження", "ув'язнення", "жертва", "негатив"],
    image: getCardImageUrl("sw08")
  },
  {
    id: 44,
    name: "Nine of Swords",
    nameUk: "Дев'ятка Мечів",
    suit: "Swords",
    number: 9,
    meaningUpright: "Anxiety, worry, fear, depression, nightmares, isolation, despair",
    meaningUprightUk: "Тривога, хвилювання, страх, депресія, кошмари, ізоляція, відчай",
    meaningReversed: "Inner turmoil, deep-seated fears, secrets, releasing worry, hope",
    meaningReversedUk: "Внутрішні потрясіння, глибоко вкорінені страхи, секрети, звільнення від хвилювання, надія",
    keywords: ["anxiety", "worry", "fear", "nightmares"],
    keywordsUk: ["тривога", "хвилювання", "страх", "кошмари"],
    image: getCardImageUrl("sw09")
  },
  {
    id: 45,
    name: "Ten of Swords",
    nameUk: "Десятка Мечів",
    suit: "Swords",
    number: 10,
    meaningUpright: "Painful endings, deep wounds, betrayal, loss, crisis, rock bottom",
    meaningUprightUk: "Болісні завершення, глибокі рани, зрада, втрата, криза, дно",
    meaningReversed: "Recovery, regeneration, resisting an inevitable end, moving on",
    meaningReversedUk: "Відновлення, регенерація, опір неминучому кінцю, рух вперед",
    keywords: ["endings", "betrayal", "crisis", "loss"],
    keywordsUk: ["завершення", "зрада", "криза", "втрата"],
    image: getCardImageUrl("sw10")
  },
  {
    id: 46,
    name: "Page of Swords",
    nameUk: "Паж Мечів",
    suit: "Swords",
    number: 11,
    meaningUpright: "New ideas, curiosity, thirst for knowledge, new ways of communicating",
    meaningUprightUk: "Нові ідеї, цікавість, спрага знань, нові способи комунікації",
    meaningReversed: "Self-expression, all talk and no action, haphazard action, haste",
    meaningReversedUk: "Самовираження, всі слова без дій, безладна дія, поспіх",
    keywords: ["curiosity", "ideas", "communication", "learning"],
    keywordsUk: ["цікавість", "ідеї", "комунікація", "навчання"],
    image: getCardImageUrl("sw11")
  },
  {
    id: 47,
    name: "Knight of Swords",
    nameUk: "Лицар Мечів",
    suit: "Swords",
    number: 12,
    meaningUpright: "Ambitious, action-oriented, driven to succeed, fast-thinking, assertive",
    meaningUprightUk: "Амбітний, орієнтований на дії, прагнучий успіху, швидко мислить, наполегливий",
    meaningReversed: "Restless, unfocused, impulsive, burn-out, aggressive, rude",
    meaningReversedUk: "Неспокійний, несфокусований, імпульсивний, вигорання, агресивний, грубий",
    keywords: ["action", "ambition", "speed", "assertiveness"],
    keywordsUk: ["дія", "амбіції", "швидкість", "наполегливість"],
    image: getCardImageUrl("sw12")
  },
  {
    id: 48,
    name: "Queen of Swords",
    nameUk: "Королева Мечів",
    suit: "Swords",
    number: 13,
    meaningUpright: "Independent, unbiased judgement, clear boundaries, direct communication",
    meaningUprightUk: "Незалежна, неупереджене судження, чіткі межі, пряме спілкування",
    meaningReversed: "Overly-emotional, easily influenced, bitchy, cold-hearted, vindictive",
    meaningReversedUk: "Надмірно емоційна, легко піддається впливу, зла, холоднокровна, мстива",
    keywords: ["independence", "clarity", "boundaries", "honesty"],
    keywordsUk: ["незалежність", "ясність", "межі", "чесність"],
    image: getCardImageUrl("sw13")
  },
  {
    id: 49,
    name: "King of Swords",
    nameUk: "Король Мечів",
    suit: "Swords",
    number: 14,
    meaningUpright: "Mental clarity, intellectual power, authority, truth, clear thinking",
    meaningUprightUk: "Ментальна ясність, інтелектуальна сила, авторитет, правда, чітке мислення",
    meaningReversed: "Quiet power, inner truth, misuse of power, manipulation, tyranny",
    meaningReversedUk: "Тиха сила, внутрішня правда, зловживання владою, маніпуляція, тиранія",
    keywords: ["clarity", "authority", "truth", "intellect"],
    keywordsUk: ["ясність", "авторитет", "правда", "інтелект"],
    image: getCardImageUrl("sw14")
  },

  // ========== WANDS (14 cards) ==========
  {
    id: 50,
    name: "Ace of Wands",
    nameUk: "Туз Жезлів",
    suit: "Wands",
    number: 1,
    meaningUpright: "Inspiration, new opportunities, growth, potential, creative spark",
    meaningUprightUk: "Натхнення, нові можливості, зростання, потенціал, творча іскра",
    meaningReversed: "Emerging ideas, lack of direction, distractions, delays, creative blocks",
    meaningReversedUk: "Зароджуючі ідеї, відсутність напрямку, відволікання, затримки, творчі блоки",
    keywords: ["inspiration", "opportunity", "potential", "growth"],
    keywordsUk: ["натхнення", "можливість", "потенціал", "зростання"],
    image: getCardImageUrl("wa01")
  },
  {
    id: 51,
    name: "Two of Wands",
    nameUk: "Двійка Жезлів",
    suit: "Wands",
    number: 2,
    meaningUpright: "Future planning, progress, decisions, discovery, personal power",
    meaningUprightUk: "Майбутнє планування, прогрес, рішення, відкриття, особиста сила",
    meaningReversed: "Personal goals, inner alignment, fear of unknown, lack of planning",
    meaningReversedUk: "Особисті цілі, внутрішнє узгодження, страх невідомого, відсутність планування",
    keywords: ["planning", "progress", "decisions", "discovery"],
    keywordsUk: ["планування", "прогрес", "рішення", "відкриття"],
    image: getCardImageUrl("wa02")
  },
  {
    id: 52,
    name: "Three of Wands",
    nameUk: "Трійка Жезлів",
    suit: "Wands",
    number: 3,
    meaningUpright: "Progress, expansion, foresight, overseas opportunities, looking ahead",
    meaningUprightUk: "Прогрес, розширення, передбачення, закордонні можливості, погляд вперед",
    meaningReversed: "Playing small, lack of foresight, unexpected delays, obstacles",
    meaningReversedUk: "Гра по-маленькому, відсутність передбачення, несподівані затримки, перешкоди",
    keywords: ["expansion", "foresight", "progress", "opportunity"],
    keywordsUk: ["розширення", "передбачення", "прогрес", "можливість"],
    image: getCardImageUrl("wa03")
  },
  {
    id: 53,
    name: "Four of Wands",
    nameUk: "Четвірка Жезлів",
    suit: "Wands",
    number: 4,
    meaningUpright: "Celebration, joy, harmony, relaxation, homecoming, achievement",
    meaningUprightUk: "Святкування, радість, гармонія, розслаблення, повернення додому, досягнення",
    meaningReversed: "Personal celebration, inner harmony, conflict with others, transition",
    meaningReversedUk: "Особисте святкування, внутрішня гармонія, конфлікт з іншими, перехід",
    keywords: ["celebration", "harmony", "joy", "homecoming"],
    keywordsUk: ["святкування", "гармонія", "радість", "повернення"],
    image: getCardImageUrl("wa04")
  },
  {
    id: 54,
    name: "Five of Wands",
    nameUk: "П'ятірка Жезлів",
    suit: "Wands",
    number: 5,
    meaningUpright: "Conflict, disagreements, competition, tension, diversity, struggle",
    meaningUprightUk: "Конфлікт, розбіжності, конкуренція, напруга, різноманіття, боротьба",
    meaningReversed: "Inner conflict, conflict avoidance, tension release, cooperation",
    meaningReversedUk: "Внутрішній конфлікт, уникнення конфлікту, зняття напруги, співпраця",
    keywords: ["conflict", "competition", "tension", "diversity"],
    keywordsUk: ["конфлікт", "конкуренція", "напруга", "різноманіття"],
    image: getCardImageUrl("wa05")
  },
  {
    id: 55,
    name: "Six of Wands",
    nameUk: "Шістка Жезлів",
    suit: "Wands",
    number: 6,
    meaningUpright: "Success, public recognition, progress, self-confidence, victory, pride",
    meaningUprightUk: "Успіх, публічне визнання, прогрес, впевненість у собі, перемога, гордість",
    meaningReversed: "Private achievement, personal definition of success, fall from grace",
    meaningReversedUk: "Особисте досягнення, власне визначення успіху, падіння з вершини",
    keywords: ["success", "recognition", "victory", "pride"],
    keywordsUk: ["успіх", "визнання", "перемога", "гордість"],
    image: getCardImageUrl("wa06")
  },
  {
    id: 56,
    name: "Seven of Wands",
    nameUk: "Сімка Жезлів",
    suit: "Wands",
    number: 7,
    meaningUpright: "Challenge, competition, protection, perseverance, defending position",
    meaningUprightUk: "Виклик, конкуренція, захист, наполегливість, захист позиції",
    meaningReversed: "Exhaustion, giving up, overwhelmed, lack of self-belief, quitting",
    meaningReversedUk: "Виснаження, здача, перевантаженість, відсутність віри в себе, залишення",
    keywords: ["challenge", "perseverance", "defense", "competition"],
    keywordsUk: ["виклик", "наполегливість", "захист", "конкуренція"],
    image: getCardImageUrl("wa07")
  },
  {
    id: 57,
    name: "Eight of Wands",
    nameUk: "Вісімка Жезлів",
    suit: "Wands",
    number: 8,
    meaningUpright: "Movement, fast-paced change, action, alignment, air travel, quick decisions",
    meaningUprightUk: "Рух, швидкі зміни, дія, узгодження, повітряні подорожі, швидкі рішення",
    meaningReversed: "Delays, frustration, resisting change, internal alignment, slow down",
    meaningReversedUk: "Затримки, фрустрація, опір змінам, внутрішнє узгодження, сповільнення",
    keywords: ["movement", "speed", "action", "alignment"],
    keywordsUk: ["рух", "швидкість", "дія", "узгодження"],
    image: getCardImageUrl("wa08")
  },
  {
    id: 58,
    name: "Nine of Wands",
    nameUk: "Дев'ятка Жезлів",
    suit: "Wands",
    number: 9,
    meaningUpright: "Resilience, courage, persistence, test of faith, boundaries, defensiveness",
    meaningUprightUk: "Стійкість, мужність, наполегливість, випробування віри, межі, захисна позиція",
    meaningReversed: "Inner resources, struggle, overwhelm, defensive, paranoia, stubbornness",
    meaningReversedUk: "Внутрішні ресурси, боротьба, перевантаженість, захисна позиція, паранойя, впертість",
    keywords: ["resilience", "persistence", "courage", "boundaries"],
    keywordsUk: ["стійкість", "наполегливість", "мужність", "межі"],
    image: getCardImageUrl("wa09")
  },
  {
    id: 59,
    name: "Ten of Wands",
    nameUk: "Десятка Жезлів",
    suit: "Wands",
    number: 10,
    meaningUpright: "Burden, extra responsibility, hard work, stress, burnout, accomplishment",
    meaningUprightUk: "Тягар, додаткова відповідальність, важка робота, стрес, вигорання, досягнення",
    meaningReversed: "Doing it all, carrying burden, delegation, release, letting go",
    meaningReversedUk: "Робити все самому, нести тягар, делегування, звільнення, відпускання",
    keywords: ["burden", "responsibility", "stress", "accomplishment"],
    keywordsUk: ["тягар", "відповідальність", "стрес", "досягнення"],
    image: getCardImageUrl("wa10")
  },
  {
    id: 60,
    name: "Page of Wands",
    nameUk: "Паж Жезлів",
    suit: "Wands",
    number: 11,
    meaningUpright: "Inspiration, ideas, discovery, limitless potential, free spirit, enthusiasm",
    meaningUprightUk: "Натхнення, ідеї, відкриття, безмежний потенціал, вільний дух, ентузіазм",
    meaningReversed: "Newly-formed ideas, redirecting energy, self-limiting beliefs, procrastination",
    meaningReversedUk: "Свіжосформовані ідеї, перенаправлення енергії, самообмежувальні переконання, прокрастинація",
    keywords: ["inspiration", "enthusiasm", "discovery", "potential"],
    keywordsUk: ["натхнення", "ентузіазм", "відкриття", "потенціал"],
    image: getCardImageUrl("wa11")
  },
  {
    id: 61,
    name: "Knight of Wands",
    nameUk: "Лицар Жезлів",
    suit: "Wands",
    number: 12,
    meaningUpright: "Energy, passion, inspired action, adventure, impulsiveness, enthusiasm",
    meaningUprightUk: "Енергія, пристрасть, натхненні дії, пригода, імпульсивність, ентузіазм",
    meaningReversed: "Passion project, haste, scattered energy, delays, frustration, recklessness",
    meaningReversedUk: "Проект пристрасті, поспіх, розпорошена енергія, затримки, фрустрація, безрозсудність",
    keywords: ["passion", "adventure", "energy", "impulsiveness"],
    keywordsUk: ["пристрасть", "пригода", "енергія", "імпульсивність"],
    image: getCardImageUrl("wa12")
  },
  {
    id: 62,
    name: "Queen of Wands",
    nameUk: "Королева Жезлів",
    suit: "Wands",
    number: 13,
    meaningUpright: "Courage, confidence, independence, social butterfly, determination, vivacious",
    meaningUprightUk: "Мужність, впевненість, незалежність, соціальна метелик, рішучість, жвава",
    meaningReversed: "Self-respect, self-confidence, introverted, re-establish sense of self, jealous",
    meaningReversedUk: "Самоповага, впевненість у собі, інтроверт, відновлення відчуття себе, ревнива",
    keywords: ["confidence", "courage", "independence", "determination"],
    keywordsUk: ["впевненість", "мужність", "незалежність", "рішучість"],
    image: getCardImageUrl("wa13")
  },
  {
    id: 63,
    name: "King of Wands",
    nameUk: "Король Жезлів",
    suit: "Wands",
    number: 14,
    meaningUpright: "Natural leader, vision, entrepreneur, honour, courage, action-oriented",
    meaningUprightUk: "Природний лідер, бачення, підприємець, честь, мужність, орієнтований на дії",
    meaningReversed: "Impulsiveness, haste, ruthless, high expectations, vicious, dictator",
    meaningReversedUk: "Імпульсивність, поспіх, безжальний, високі очікування, жорстокий, диктатор",
    keywords: ["leadership", "vision", "courage", "entrepreneur"],
    keywordsUk: ["лідерство", "бачення", "мужність", "підприємець"],
    image: getCardImageUrl("wa14")
  },

  // ========== PENTACLES (14 cards) ==========
  {
    id: 64,
    name: "Ace of Pentacles",
    nameUk: "Туз Пентаклів",
    suit: "Pentacles",
    number: 1,
    meaningUpright: "Manifestation, abundance, opportunity, prosperity, new financial venture",
    meaningUprightUk: "Втілення, достаток, можливість, процвітання, нове фінансове підприємство",
    meaningReversed: "Lost opportunity, lack of planning, scarcity mindset, poor financial prospects",
    meaningReversedUk: "Втрачена можливість, відсутність планування, менталітет дефіциту, погані фінансові перспективи",
    keywords: ["opportunity", "abundance", "prosperity", "manifestation"],
    keywordsUk: ["можливість", "достаток", "процвітання", "втілення"],
    image: getCardImageUrl("pe01")
  },
  {
    id: 65,
    name: "Two of Pentacles",
    nameUk: "Двійка Пентаклів",
    suit: "Pentacles",
    number: 2,
    meaningUpright: "Multiple priorities, time management, prioritization, adaptability, balance",
    meaningUprightUk: "Багато пріоритетів, управління часом, пріоритизація, адаптивність, баланс",
    meaningReversed: "Over-committed, disorganization, reprioritization, overwhelm, chaos",
    meaningReversedUk: "Надмірна зайнятість, дезорганізація, перепріоритизація, перевантаженість, хаос",
    keywords: ["balance", "adaptability", "priorities", "flexibility"],
    keywordsUk: ["баланс", "адаптивність", "пріоритети", "гнучкість"],
    image: getCardImageUrl("pe02")
  },
  {
    id: 66,
    name: "Three of Pentacles",
    nameUk: "Трійка Пентаклів",
    suit: "Pentacles",
    number: 3,
    meaningUpright: "Teamwork, collaboration, learning, implementation, skill development",
    meaningUprightUk: "Командна робота, співпраця, навчання, реалізація, розвиток навичок",
    meaningReversed: "Disharmony, misalignment, working alone, lack of teamwork, ego",
    meaningReversedUk: "Дисгармонія, неузгодженість, робота наодинці, відсутність командної роботи, его",
    keywords: ["teamwork", "collaboration", "skill", "learning"],
    keywordsUk: ["командна-робота", "співпраця", "навичка", "навчання"],
    image: getCardImageUrl("pe03")
  },
  {
    id: 67,
    name: "Four of Pentacles",
    nameUk: "Четвірка Пентаклів",
    suit: "Pentacles",
    number: 4,
    meaningUpright: "Saving money, security, conservatism, scarcity, control, possessiveness",
    meaningUprightUk: "Збереження грошей, безпека, консерватизм, дефіцит, контроль, власницькість",
    meaningReversed: "Over-spending, greed, self-protection, financial insecurity, letting go",
    meaningReversedUk: "Надмірні витрати, жадібність, самозахист, фінансова небезпека, відпускання",
    keywords: ["security", "control", "conservation", "possessiveness"],
    keywordsUk: ["безпека", "контроль", "збереження", "власницькість"],
    image: getCardImageUrl("pe04")
  },
  {
    id: 68,
    name: "Five of Pentacles",
    nameUk: "П'ятірка Пентаклів",
    suit: "Pentacles",
    number: 5,
    meaningUpright: "Financial loss, poverty, lack mindset, isolation, worry, hardship",
    meaningUprightUk: "Фінансова втрата, бідність, менталітет нестачі, ізоляція, хвилювання, труднощі",
    meaningReversed: "Recovery from financial loss, spiritual poverty, positive changes, overcoming adversity",
    meaningReversedUk: "Відновлення від фінансової втрати, духовна бідність, позитивні зміни, подолання труднощів",
    keywords: ["hardship", "poverty", "isolation", "worry"],
    keywordsUk: ["труднощі", "бідність", "ізоляція", "хвилювання"],
    image: getCardImageUrl("pe05")
  },
  {
    id: 69,
    name: "Six of Pentacles",
    nameUk: "Шістка Пентаклів",
    suit: "Pentacles",
    number: 6,
    meaningUpright: "Giving, receiving, sharing wealth, generosity, charity, balance",
    meaningUprightUk: "Віддавання, отримання, ділення багатством, щедрість, благодійність, баланс",
    meaningReversed: "Self-care, unpaid debts, one-sided charity, power dynamics, inequality",
    meaningReversedUk: "Самодопомога, несплачені борги, однобічна благодійність, динаміка влади, нерівність",
    keywords: ["generosity", "charity", "giving", "balance"],
    keywordsUk: ["щедрість", "благодійність", "віддавання", "баланс"],
    image: getCardImageUrl("pe06")
  },
  {
    id: 70,
    name: "Seven of Pentacles",
    nameUk: "Сімка Пентаклів",
    suit: "Pentacles",
    number: 7,
    meaningUpright: "Long-term view, sustainable results, perseverance, investment, patience",
    meaningUprightUk: "Довгостроковий погляд, стійкі результати, наполегливість, інвестиції, терпіння",
    meaningReversed: "Lack of long-term vision, limited success, impatience, anxiety, frustration",
    meaningReversedUk: "Відсутність довгострокового бачення, обмежений успіх, нетерпіння, тривога, фрустрація",
    keywords: ["patience", "investment", "perseverance", "long-term"],
    keywordsUk: ["терпіння", "інвестиції", "наполегливість", "довгостроковий"],
    image: getCardImageUrl("pe07")
  },
  {
    id: 71,
    name: "Eight of Pentacles",
    nameUk: "Вісімка Пентаклів",
    suit: "Pentacles",
    number: 8,
    meaningUpright: "Apprenticeship, repetitive tasks, mastery, skill development, diligence",
    meaningUprightUk: "Учнівство, повторювані завдання, майстерність, розвиток навичок, старанність",
    meaningReversed: "Self-development, perfectionism, misdirected activity, lack of focus",
    meaningReversedUk: "Саморозвиток, перфекціонізм, неправильно спрямована діяльність, відсутність фокусу",
    keywords: ["mastery", "skill", "diligence", "craftsmanship"],
    keywordsUk: ["майстерність", "навичка", "старанність", "ремесло"],
    image: getCardImageUrl("pe08")
  },
  {
    id: 72,
    name: "Nine of Pentacles",
    nameUk: "Дев'ятка Пентаклів",
    suit: "Pentacles",
    number: 9,
    meaningUpright: "Abundance, luxury, self-sufficiency, financial independence, success, rewards",
    meaningUprightUk: "Достаток, розкіш, самодостатність, фінансова незалежність, успіх, нагороди",
    meaningReversed: "Self-worth, over-investment in work, hustling, lifestyle creep, materialism",
    meaningReversedUk: "Самооцінка, надмірні інвестиції в роботу, метушіння, зростання витрат, матеріалізм",
    keywords: ["abundance", "luxury", "independence", "success"],
    keywordsUk: ["достаток", "розкіш", "незалежність", "успіх"],
    image: getCardImageUrl("pe09")
  },
  {
    id: 73,
    name: "Ten of Pentacles",
    nameUk: "Десятка Пентаклів",
    suit: "Pentacles",
    number: 10,
    meaningUpright: "Wealth, financial security, family, long-term success, legacy, contribution",
    meaningUprightUk: "Багатство, фінансова безпека, сім'я, довгостроковий успіх, спадщина, внесок",
    meaningReversed: "Financial failure, loneliness, loss, breaking traditions, family discord",
    meaningReversedUk: "Фінансова невдача, самотність, втрата, порушення традицій, сімейний розбрат",
    keywords: ["wealth", "legacy", "family", "security"],
    keywordsUk: ["багатство", "спадщина", "сім'я", "безпека"],
    image: getCardImageUrl("pe10")
  },
  {
    id: 74,
    name: "Page of Pentacles",
    nameUk: "Паж Пентаклів",
    suit: "Pentacles",
    number: 11,
    meaningUpright: "Manifestation, financial opportunity, skill development, new ideas, ambition",
    meaningUprightUk: "Втілення, фінансова можливість, розвиток навичок, нові ідеї, амбіції",
    meaningReversed: "Lack of progress, procrastination, learn from failure, poor planning",
    meaningReversedUk: "Відсутність прогресу, прокрастинація, навчання на помилках, погане планування",
    keywords: ["opportunity", "ambition", "learning", "manifestation"],
    keywordsUk: ["можливість", "амбіції", "навчання", "втілення"],
    image: getCardImageUrl("pe11")
  },
  {
    id: 75,
    name: "Knight of Pentacles",
    nameUk: "Лицар Пентаклів",
    suit: "Pentacles",
    number: 12,
    meaningUpright: "Hard work, productivity, routine, conservatism, patience, responsibility",
    meaningUprightUk: "Важка робота, продуктивність, рутина, консерватизм, терпіння, відповідальність",
    meaningReversed: "Self-discipline, boredom, feeling 'stuck', perfectionism, frustration",
    meaningReversedUk: "Самодисципліна, нудьга, відчуття 'застрягання', перфекціонізм, фрустрація",
    keywords: ["hard-work", "responsibility", "routine", "patience"],
    keywordsUk: ["важка-робота", "відповідальність", "рутина", "терпіння"],
    image: getCardImageUrl("pe12")
  },
  {
    id: 76,
    name: "Queen of Pentacles",
    nameUk: "Королева Пентаклів",
    suit: "Pentacles",
    number: 13,
    meaningUpright: "Nurturing, practical, providing financially, down-to-earth, sensible, luxury",
    meaningUprightUk: "Турботлива, практична, фінансово забезпечує, приземлена, розумна, розкіш",
    meaningReversed: "Financial independence, self-care, work-home conflict, smothering, jealousy",
    meaningReversedUk: "Фінансова незалежність, самодопомога, конфлікт робота-дім, надмірна опіка, ревнощі",
    keywords: ["nurturing", "practical", "abundance", "security"],
    keywordsUk: ["турбота", "практичність", "достаток", "безпека"],
    image: getCardImageUrl("pe13")
  },
  {
    id: 77,
    name: "King of Pentacles",
    nameUk: "Король Пентаклів",
    suit: "Pentacles",
    number: 14,
    meaningUpright: "Wealth, business, leadership, security, discipline, abundance, prosperity",
    meaningUprightUk: "Багатство, бізнес, лідерство, безпека, дисципліна, достаток, процвітання",
    meaningReversed: "Financially inept, obstinate, flashy, poor financial decisions, greedy",
    meaningReversedUk: "Фінансово некомпетентний, впертий, показний, погані фінансові рішення, жадібний",
    keywords: ["wealth", "leadership", "prosperity", "discipline"],
    keywordsUk: ["багатство", "лідерство", "процвітання", "дисципліна"],
    image: getCardImageUrl("pe14")
  }
];

module.exports = { tarotCards };
